using System;
using Crop.Data;
using Inventory.Item;
using UnityEngine;
using Utility;
namespace Crop.Logic
{
    public class CropManager : MonoBehaviour
    {
        public CropDataListSo cropDataListSo;
        /// <summary>
        /// crop éƒ½ç”Ÿæˆåœ¨è¿™ä¸ªå­èŠ‚ç‚¹ä¸‹
        /// </summary>
        private Transform _cropParent;
        /// <summary>
        /// å½“å‰çš„ç½‘æ ¼
        /// </summary>
        private Grid _currentGrid;

        private Season _currentSeason;

        private void OnEnable()
        {
            MyEventHandler.PlantSeedEvent += OnPlantSeedEvent;
            MyEventHandler.AfterSceneLoadEvent += OnAfterSceneLoadEvent;
            MyEventHandler.GameDayEvent += OnGameDayEvent;
        }

        private void OnDisable()
        {
            MyEventHandler.PlantSeedEvent -= OnPlantSeedEvent;
            MyEventHandler.AfterSceneLoadEvent -= OnAfterSceneLoadEvent;
            MyEventHandler.GameDayEvent -= OnGameDayEvent;
        }
        private void OnGameDayEvent(int day, Season season)
        {
            _currentSeason = season;
        }
        private void OnAfterSceneLoadEvent()
        {
            _currentGrid = FindObjectOfType<Grid>();
            _cropParent = GameObject.FindWithTag("CropParent").transform;
        }
        private void OnPlantSeedEvent(int id, TileDetails tileDetails)
        {
            CropDetails cropDetails = GetCropDetails(id);
            if (cropDetails != null && SeasonAvailable(cropDetails) && tileDetails.seedItemId == -1)
            {
                tileDetails.seedItemId = id;
                tileDetails.growthDays = 0;
                // æ˜¾ç¤ºä½œç‰©
                DisplayCropPlant(tileDetails,cropDetails);
            }
            else if (tileDetails.seedItemId != -1)
            {
                // æœ‰å†œä½œç‰©çš„
                // æ˜¾ç¤ºä½œç‰©
                // åˆ·æ–°ä¸€ä¸‹
                DisplayCropPlant(tileDetails,cropDetails);
            }
        }

        /// <summary>
        /// ç”Ÿæˆä¸€ä¸‹
        /// </summary>
        /// <param name="tileDetails"></param>
        /// <param name="cropDetails"></param>
        private void DisplayCropPlant(TileDetails tileDetails, CropDetails cropDetails)
        {
            // æˆé•¿é˜¶æ®µ
            int growthStages = cropDetails.growthDays.Length;
            int currentStage = 0;
            int dayCounter = cropDetails.TotalGrowthDays;
            
            // å€’å™ å·§å¦™çš„é€»è¾‘ ğŸ˜
            for (int i = growthStages - 1; i >= 0; i--)
            {
                if (tileDetails.growthDays >= dayCounter)
                {
                    // æ‰“é€šå…³äº†
                    currentStage = i;
                    break;
                }
                dayCounter -= cropDetails.growthDays[i];
            }
            
            // è·å–å½“å‰é˜¶æ®µçš„Prefab
            GameObject currenPrefab = cropDetails.growthPreFab[currentStage];
            // è·å–å½“å‰é˜¶æ®µçš„å›¾ç‰‡
            Sprite currentSprite = cropDetails.growthSprites[currentStage];
            // ç“¦ç‰‡çš„XY å·¦ä¸‹è§’çš„ç‚¹
            Vector3 pos = new Vector3(tileDetails.pos.x + 0.5f, tileDetails.pos.y + 0.5f, 0);
            GameObject cropInstance = Instantiate(currenPrefab,pos, Quaternion.identity,_cropParent);

            cropInstance.GetComponentInChildren<SpriteRenderer>().sprite = currentSprite;

        }

        private CropDetails GetCropDetails(int id)
        {
            return cropDataListSo.cropDataList.Find(details => id == details.seedItemID );
        }

        /// <summary>
        /// åˆ¤æ–­å½“å‰çš„å­£èŠ‚æ˜¯å¦å¯ä»¥ç§æ¤
        /// </summary>
        /// <param name="cropDetails">ç§å­çš„è¯¦æƒ…</param>
        /// <returns></returns>
        private bool SeasonAvailable(CropDetails cropDetails)
        {
            for (int i = 0; i < cropDetails.seasons.Length; i++)
            {
                if(cropDetails.seasons[i] == _currentSeason)
                {
                    return true;
                }
            }
            return false;
        }
    }
}
